version: "3.3"
services:
  api:
    build: project/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - "./project:/code"
    depends_on:
      - db
      - kafka
      - zookeeper
  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    hostname: kafka
    restart: "always"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper
  listener:
    build: listener/
    command: python message_checker.py
    environment:
      KAFKA: kafka:9092
    depends_on:
      - api
      - zookeeper
      - kafka
    volumes:
      - "./listener:/code"
 