# Generated by Django 4.0.4 on 2022-05-27 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='sample text', max_length=1024, verbose_name='Текст сообщения')),
                ('status', models.CharField(blank=True, choices=[('review', 'Review'), ('blocked', 'Blocked'), ('correct', 'Correct')], default='review', max_length=10, verbose_name='Статус сообщения')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
