# Generated by Django 4.0.4 on 2022-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='sample text', max_length=1024)),
                ('status', models.CharField(choices=[('1', 'review'), ('2', 'blocked'), ('3', 'correct')], default='1', max_length=2)),
            ],
        ),
    ]
